apiVersion: v1
kind: ConfigMap
metadata:
  name: megafile-ingress-configmap
  namespace: kube-system
data:
  client-max-body-size: 0
  client-body-buffer-size: 1024M
  enable-vts-status: "true"
  log-format-upstream: '{ "timestamp": "$time_iso8601", "remote_addr": "$remote_addr",
    "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
    "status": $status, "request_uri": "$request_uri", "uri": "$uri", "method": "$request_method",
    "referer": "$http_referer", "http_user_agent": "$http_user_agent", "host": "$host",
    "upstream_addr": "$upstream_addr", "upstream_status": "$upstream_status" }'
  proxy-buffering: True
  proxy-buffer-size: 4k
  proxy-buffers: "16 1M"
  proxy-max-temp-file-size: 0
  proxy-read-timeout: 3h
  http2: False
  upstream-keepalive-connections: "1000"
  #worker-shutdown-timeout: "300"
